### ISSUE TITLE
A missing exponential part in the calculation of the quantity cv

### ISSUE THREAD

**Issue by phiradet** [parthatalukdar/junto#3]
Dear all,

At the line number 161-162 of the file Vertex.scala, it is the implementation of the quantity c<sub>v</sub> as described in the section 2.2 [1]. 

```scala
val ent = GetNeighborhoodEntropy(neighborClone)
var cv = math.log(beta) / math.log(beta + ent)
```

In the original paper, the entropy, denoted by the variable *ent*, is passed to a function f(x). The definition of the function is f(*ent*) = log(beta)/log(beta + e^(*ent*)). By the way, the line didn't implement the natural exponential part. I am just a beginner Scala programmer. I think it may be a mistake. Do you have any idea about this point?

Many thanks,
Phiradet

[1] Talukdar, P. P., & Crammer, K. (2009). New Regularized Algorithms for Transductive Learning. In Proceedings of the European Conference on Machine Learning and Knowledge Discovery in Databases: Part II (pp. 442–457). Berlin, Heidelberg: Springer-Verlag.

**Comment by parthatalukdar** [comment]
On Wed, Feb 18, 2015 at 1:48 PM, phiradet <notifications@github.com> wrote:

> At the line number 161-162 of the file Vertex.scala, it is the
> implementation of the quantity cv as described in the section 2.2 [1].
>
> val ent = GetNeighborhoodEntropy(neighborClone)var cv = math.log(beta) / math.log(beta + ent)
>
> In the original paper, the entropy, denoted by the variable *ent*, is
> passed to a function f(x). The definition of the function is f(*ent*) =
> log(beta)/log(beta + e^(*ent*)). By the way, the line didn't implement
> the natural exponential part. I am just a beginner Scala programmer. I
> think it may be a mistake. Do you have any idea about this point?
>
Thanks for pointing this out. The random walk probability formulas used in
the paper are just one reference and by no means the only one. The user is
welcome to substitute that with her own as long as they are valid
probabilities.

Partha

**Comment by phiradet** [comment]
I got it. Thank you very much for your suggestion.

Phiradet
