### ISSUE TITLE
Incompatibility with Oracle Java 8

### ISSUE THREAD

**Issue by afshinrahimi** [parthatalukdar/junto#4]
Hello,

Thank you for the amazing work!
I was just compiling Junto with Java Oracle 8. It seems that there are some incompatibilities.
JAVA VERSION: 
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

ERROR:
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading project definition from /home/af/Documents/junto-master/project
[info] Set current project to junto (in build file:/home/af/Documents/junto-master/)
[info] Updating {file:/home/af/Documents/junto-master/}default-752ee9...
[info] Resolving org.scala-lang#scala-library;2.10.0 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.1.0 ...
[info] Resolving com.typesafe#config;1.0.0 ...
[info] Resolving org.clapper#argot_2.10;1.0.0 ...
[info] Resolving org.clapper#grizzled-scala_2.10;1.1.2 ...
[info] Resolving jline#jline;2.6 ...
[info] Resolving net.sf.trove4j#trove4j;3.0.3 ...
[info] Resolving com.typesafe#scalalogging-log4j_2.10;1.0.1 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.0 ...
[info] Resolving org.apache.logging.log4j#log4j-api;2.0-beta3 ...
[info] Done updating.
[success] Total time: 1 s, completed 04/03/2015 4:36:49 PM
[info] Compiling 11 Scala sources and 28 Java sources to /home/af/Documents/junto-master/target/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.0. Compiling...
error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
error: error while loading Comparator, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/util/Comparator.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 20)
error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 76)
error: error while loading Arrays, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/util/Arrays.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 765)
/tmp/sbt_713306da/API.scala:384: error: java.util.Comparator does not take type parameters
	private[this] val sortClasses = new Comparator[Symbol] {
                                            ^
5 errors found
[error] (compile:compile) Error compiling sbt component 'compiler-interface'
[error] Total time: 4 s, completed 04/03/2015 4:36:54 PM

It beautifully compiles and runs on OpenJDK-7 though.

Cheers.

**Comment by parthatalukdar** [comment]
Is this still an issue?

Partha

**Comment by jose1003** [comment]
Change to scala 2.10.4

**Comment by eponvert** [comment]
I noticed @jose1003's suggestion and submitted #5 to fix

**Comment by hmontenegro** [comment]
Could you please tag a release version with the fix?
